# Generated by Django 3.0.3 on 2020-08-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200827_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='img_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='img_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='img_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
