# Generated by Django 3.0.3 on 2020-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200827_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame_description',
            field=models.TextField(null=True),
        ),
    ]
