# Generated by Django 3.0.3 on 2020-09-03 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0006_auto_20200901_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_questions', models.IntegerField()),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Frame')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Subject')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Test')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
