# Generated by Django 3.0.3 on 2020-09-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_test_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Frame'),
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Topic'),
        ),
    ]
